CREATE DATABASE Redlock;
USE Redlock;
CREATE TABLE  users(
	ID INT PRIMARY KEY NOT NULL,
	 Nama VARCHAR (77) NOT NULL,
	Alamat VARCHAR (77) NOT NULL,
	Jabatan VARCHAR (77) NOT NULL
);

INSERT INTO users VALUES
(5 ,  "PETIK", "GHOHO" , "SFSD");


